# <a id="TableOfContents"></a>Table of contents

* [Certification](#Certification)
* [The Problem](#TheProblem)
* [Import Libraries](#ImportLibraries)
* [Create and Display Matrices](#CreateAndDisplayMatrices)
* [Solve the Equation with SciPy](#SolveTheEquationWithSciPy)
* [Confirm the Solution](#ConfirmTheSolution)
* [Final Answer](#FinalAnswer)

# <a id="Certification"></a>Certification 



Your output file must contain the following certification:

> I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. - Ben Smith

# <a id="TheProblem"></a>The Problem

Solve for x, y, and z for the following system of equations.

3x + 4y + 3z = 10

9x - 10y - 10z = -11

4x + 15y +18z = 37

### <a id="ImportLibraries"></a>Import Libraries 

Begin by importing the necessary libraries.

In [1]:
import numpy as np
from scipy import linalg

### <a id="CreateAndDisplayMatrices"></a>Create and Display Matrices

Next, create matrices corresponding to the given system of equations using numpy's `array` function and display them with the `print` function.  

In [2]:
A = np.array([[3, 4, 3], [9, -10, -10], [4, 15, 18]])
print(A)

[[  3   4   3]
 [  9 -10 -10]
 [  4  15  18]]


In [3]:
b = np.array([[10], [-11], [37]])
print(b)

[[ 10]
 [-11]
 [ 37]]


### <a id="SolveTheEquationWithSciPy"></a>Solve the Equation with SciPy

Finally, call the `solve` function from SciPy's linear algebra module to compute the solution to the system, then display it using the `print` function. 

In [4]:
xyz = np.linalg.solve(A,b)
print(xyz)

[[1.]
 [1.]
 [1.]]


### <a id="ConfirmTheSolution"></a>Confirm the Solution

To confirm that the solution is correct, compute the dot matrix between the `A` matrix and the solution `xyz` matrix. If the result matches the original `b` matrix, the solution is correct.  

In [5]:
print(A.dot(xyz))

[[ 10.]
 [-11.]
 [ 37.]]


This is the equivalent of solving the following:

$\begin{equation*}
\begin{vmatrix}
\mathbf{3} & \mathbf{4} & \mathbf{3} \\
\mathbf{9} & \mathbf{-10} & \mathbf{-10} \\
\mathbf{4} & \mathbf{15} & \mathbf{18}
\end{vmatrix}
\begin{vmatrix}
\mathbf{x} \\
\mathbf{y} \\
\mathbf{z}
\end{vmatrix} = 
\begin{vmatrix}
\mathbf{10} \\
\mathbf{-11} \\
\mathbf{37}
\end{vmatrix}
\end{equation*}$

$\begin{equation*}
\begin{vmatrix}
\mathbf{3} & \mathbf{4} & \mathbf{3} \\
\mathbf{9} & \mathbf{-10} & \mathbf{-10} \\
\mathbf{4} & \mathbf{15} & \mathbf{18}
\end{vmatrix}
\begin{vmatrix}
\mathbf{1} \\
\mathbf{1} \\
\mathbf{1}
\end{vmatrix} =
\begin{vmatrix}
\mathbf{10} \\
\mathbf{-11} \\
\mathbf{37}
\end{vmatrix}
\end{equation*}$

$\begin{equation*}
\begin{vmatrix}
\mathbf{10} \\
\mathbf{-11} \\
\mathbf{37}
\end{vmatrix} =
\begin{vmatrix}
\mathbf{10} \\
\mathbf{-11} \\
\mathbf{37}
\end{vmatrix}
\end{equation*}$

...which is the matrix operations equivalent of plugging each solution value back into the original equation, then simplifying to confirm that the two sides are equal.

### <a id="FinalAnswer"></a>Final Answer

x = 1
  
y = 1 
  
z = 1