# <a id="TableOfContents"></a>Table of contents

* [Certification](#Certification)
* [The Problem](#TheProblem)
* [Import Libraries](#ImportLibraries)
* [Create and Display Matrices](#CreateAndDisplayMatrices)
* [Solve the Equation with SciPy](#SolveTheEquationWithSciPy)
* [Confirm the Solution](#ConfirmTheSolution)
* [Final Answer](#FinalAnswer)

# <a id="Certification"></a>Certification 



Your output file must contain the following certification:

> I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. - Ben Smith

# <a id="TheProblem"></a>The Problem

Solve for v, w, x, y, and z for the following system of equations.

16v +17w +12x  +66y +45z = 156  

 29v -18w -15x  +73y +70z = 139  
 
-14v +46w -27x  +58y +91z = 154  

 33v +37w +24x -123y +54z =  25  
 
 20v -27w +18x  +19y -56z = -26  

### <a id="ImportLibraries"></a>Import Libraries 

Begin by importing the necessary libraries.

In [3]:
import numpy as np
from scipy import linalg

### <a id="CreateAndDisplayMatrices"></a>Create and Display Matrices

Next, create matrices corresponding to the given system of equations using numpy's `array` function and display them with the `print` function.  

In [5]:
A = np.array([[16, 17, 12, 66, 45],
              [29, -18, -15, 73, 70],
              [-14, 46, -27, 58, 91],
              [33, 37, 24, -123, 54],
              [20, -27, 18, 19, -56]])
print(A)

[[  16   17   12   66   45]
 [  29  -18  -15   73   70]
 [ -14   46  -27   58   91]
 [  33   37   24 -123   54]
 [  20  -27   18   19  -56]]


In [6]:
b = np.array([[156], [139], [154], [25], [-26]])
print(b)

[[156]
 [139]
 [154]
 [ 25]
 [-26]]


### <a id="SolveTheEquationWithSciPy"></a>Solve the Equation with SciPy

Finally, call the `solve` function from SciPy's linear algebra module to compute the solution to the system, then display it using the `print` function. 

In [7]:
vwxyz = np.linalg.solve(A,b)
print(vwxyz)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### <a id="ConfirmTheSolution"></a>Confirm the Solution

To confirm that the solution is correct, compute the dot matrix between the `A` matrix and the solution `xyz` matrix. If the result matches the original `b` matrix, the solution is correct.  

In [8]:
print(A.dot(vwxyz))

[[156.]
 [139.]
 [154.]
 [ 25.]
 [-26.]]


This is the equivalent of solving the following:

$\begin{equation*}
\begin{vmatrix}
\mathbf{16} & \mathbf{17} & \mathbf{12} & \mathbf{66} & \mathbf{45} \\
\mathbf{29} & \mathbf{-18} & \mathbf{-15} & \mathbf{73} & \mathbf{70} \\
\mathbf{-14} & \mathbf{46} & \mathbf{-27} & \mathbf{58} & \mathbf{91} \\
\mathbf{33} & \mathbf{37} & \mathbf{24} & \mathbf{-123} & \mathbf{54} \\
\mathbf{20} & \mathbf{-27} & \mathbf{18} & \mathbf{19} & \mathbf{-56} \\
\end{vmatrix}
\begin{vmatrix}
\mathbf{v} \\
\mathbf{w} \\
\mathbf{x} \\
\mathbf{y} \\
\mathbf{z}
\end{vmatrix} = 
\begin{vmatrix}
\mathbf{156} \\
\mathbf{139} \\
\mathbf{154} \\
\mathbf{25} \\
\mathbf{-26}
\end{vmatrix}
\end{equation*}$

$\begin{equation*}
\begin{vmatrix}
\mathbf{16} & \mathbf{17} & \mathbf{12} & \mathbf{66} & \mathbf{45} \\
\mathbf{29} & \mathbf{-18} & \mathbf{-15} & \mathbf{73} & \mathbf{70} \\
\mathbf{-14} & \mathbf{46} & \mathbf{-27} & \mathbf{58} & \mathbf{91} \\
\mathbf{33} & \mathbf{37} & \mathbf{24} & \mathbf{-123} & \mathbf{54} \\
\mathbf{20} & \mathbf{-27} & \mathbf{18} & \mathbf{19} & \mathbf{-56} \\
\end{vmatrix}
\begin{vmatrix}
\mathbf{1} \\
\mathbf{1} \\
\mathbf{1} \\
\mathbf{1} \\
\mathbf{1}
\end{vmatrix} = 
\begin{vmatrix}
\mathbf{156} \\
\mathbf{139} \\
\mathbf{154} \\
\mathbf{25} \\
\mathbf{-26}
\end{vmatrix}
\end{equation*}$

$\begin{equation*}
\begin{vmatrix}
\mathbf{156} \\
\mathbf{139} \\
\mathbf{154} \\
\mathbf{25} \\
\mathbf{-26}
\end{vmatrix} =
\begin{vmatrix}
\mathbf{156} \\
\mathbf{139} \\
\mathbf{154} \\
\mathbf{25} \\
\mathbf{-26}
\end{vmatrix}
\end{equation*}$

Which is the matrix operations equivalent of plugging each solution value back into the original equation, then simplifying to confirm that the two sides are equal.

### <a id="FinalAnswer"></a>Final Answer
v = 1  
  
w = 1  
  
x = 1  
  
y = 1  
  
z = 1